### ISSUE TITLE
Access denied to: http://coova-dev.s3.amazonaws.com/mvn

### ISSUE THREAD

**Issue by mmoayyed** [coova/jradius#1]
```bash
[ERROR] Failed to execute goal on project cas-server-support-radius: Could not resolve dependencies for project org.jasig.cas:cas-server-support-radius:jar:4.1.0-RC3-SNAPSHOT: Failed to collect dependencies at net.jradius:jradius-core:jar:1.1.3: Failed to read artifact descriptor for net.jradius:jradius-core:jar:1.1.3: Could not transfer artifact net.jradius:jradius-core:pom:1.1.3 from/to coova (http://coova-dev.s3.amazonaws.com/mvn): Access denied to: http://coova-dev.s3.amazonaws.com/mvn/net/jradius/jradius-core/1.1.3/jradius-core-1.1.3.pom , ReasonPhrase:Forbidden. -> [Help 1]
```

**Comment by lindseysEmmanuel** [comment]
I am getting that same error. Does anyone know the cause and how to resolve it? Been attempting to troubleshoot this error for 3 days with no luck. All I know is the Apereo CAS RADIUS Support cannot connect for some reason.

Thought this link would help but it didn't: https://cwiki.apache.org/confluence/display/maven/dependencyresolutionexception

**Comment by wlanmac** [comment]
You will need to find a different repo to use... The source is at https://github.com/coova/jradius but there is no longer a repo in aws.

**Comment by spaetow** [comment]
David, can you publish it to Maven Central please? That way it's right where people use it. :-)

**Comment by mmoayyed** [comment]
@wlanmac Problem is, there are no other repos, short of one actually creating or installing the jar directly into the maven local cache. Since the project is maven based and you do releases, it would be ideal if you simply published snapshots and releases into maven central.

**Comment by mvrueden** [comment]
I encountered the same issue. Gladly we already set up a maven mirror for the original repository. However, we only have version 1.1.4 available. For those who are using 1.1.4 are welcome to use our mirror for now: http://maven.opennms.org/content/repositories/coova/

**Comment by wlanmac** [comment]
Thanks!

**Comment by mmoayyed** [comment]
We ended up using jitpack. If you keep releasing to github, that would work just fine.

**Comment by jkacer** [comment]
It would be great to have older versions also available in the JitPack repository.
For example, CAS 4.0.x and 4.1.x still depend on version 1.0.0.

**Comment by spaetow** [comment]
You would be well-advised to switch to 1.1.4 or higher...

**Comment by MwumLi** [comment]
@jkacer  Do you know where can find jradius@1.0.0
@spaetow  The compilation will report more error when switch 1.14 or higher

**Comment by MwumLi** [comment]
@jkacer I have found net.jradius@1.0.0 in <http://maven.it.su.se/nexus/content/groups/public>  😀
if you come here for cas compilation question, you can add below in `~/.m2/setting ` to solve it:  

```xml
   <mirror>
      <id>jradius1.0.0</id>
      <mirrorOf>coova</mirrorOf>
      <name>jradius1.0</name>
      <url>http://maven.it.su.se/nexus/content/groups/public</url>
    </mirror>
```

**Comment by spaetow** [comment]
@MwumLi, then those compilation errors should be resolved rather than going back to 1.0.0.

**Comment by jkacer** [comment]
Hi @MwumLi !
I'm glad you have already found it. Back then, I solved the problem by using a local copy of the library and uploading it into our company's Artifactory, so the build process found it. I was not able to find it anywhere on the Internet. Thank you for sharing the repository URL with us :-)

**Comment by EvanPro** [comment]
> @jkacer I have found net.jradius@1.0.0 in http://maven.it.su.se/nexus/content/groups/public 😀
> if you come here for cas compilation question, you can add below in `~/.m2/setting ` to solve it:
> 
> ```
>    <mirror>
>       <id>jradius1.0.0</id>
>       <mirrorOf>coova</mirrorOf>
>       <name>jradius1.0</name>
>       <url>http://maven.it.su.se/nexus/content/groups/public</url>
>     </mirror>
> ```

Hi @MwumLi !
It does not work now , could you provide another one？:)
