### ISSUE TITLE
JRadiusSimulator pap:Auth: (0) Login incorrect (pap: Cleartext password does not match "known good" password)

### ISSUE THREAD

**Issue by yunyexiangfeng** [coova/jradius#36]
when i use JRadiusSimulator  send request with upd and pap  to freeradius directly，the user steve/testing in /etc/raddb/user file can login well. The sbin/radiusd -X console can print user-name and user-password normally.
when i use JRadiusSimulator  send request with radsec and pap, the same user, i get a wrong message on freeradius-server-3.0.17 console.
In this way, JRadiusSimulator  send request to jradius server, then the server parse the request to udp packet and send the packet to freeradius server. The console print user-password like this:
(0) Received Access-Request Id 15 from 127.0.0.1:40514 to 127.0.0.1:1812 length 69
(0)   User-Name = "steve"
(0)   NAS-IP-Address = 127.0.0.1
(0)   User-Password = "W\025\341#\232\213\250\346<c]+\225\376m\220"
(0)   Message-Authenticator = 0xef989dfb67b6524c29233033fa610819
(0) # Executing section authorize from file /opt/OmniVista_2500_NMS/services/freeradius-server/etc/raddb/sites-enabled/default
(0)   authorize {
(0)     policy filter_username {
(0)       if (&User-Name) {
(0)       if (&User-Name)  -> TRUE
(0)       if (&User-Name)  {
(0)         if (&User-Name =~ / /) {
(0)         if (&User-Name =~ / /)  -> FALSE
(0)         if (&User-Name =~ /@[^@]*@/ ) {
(0)         if (&User-Name =~ /@[^@]*@/ )  -> FALSE
(0)         if (&User-Name =~ /\.\./ ) {
(0)         if (&User-Name =~ /\.\./ )  -> FALSE
(0)         if ((&User-Name =~ /@/) && (&User-Name !~ /@(.+)\.(.+)$/))  {
(0)         if ((&User-Name =~ /@/) && (&User-Name !~ /@(.+)\.(.+)$/))   -> FALSE
(0)         if (&User-Name =~ /\.$/)  {
(0)         if (&User-Name =~ /\.$/)   -> FALSE
(0)         if (&User-Name =~ /@\./)  {
(0)         if (&User-Name =~ /@\./)   -> FALSE
(0)       } # if (&User-Name)  = notfound
(0)     } # policy filter_username = notfound
(0)     [preprocess] = ok
(0)     [chap] = noop
(0)     [mschap] = noop
(0)     [digest] = noop
(0) suffix: Checking for suffix after "@"
(0) suffix: No '@' in User-Name = "steve", looking up realm NULL
(0) suffix: No such realm "NULL"
(0)     [suffix] = noop
(0) eap: No EAP-Message, not doing EAP
(0)     [eap] = noop
(0) files: users: Matched entry steve at line 73
(0)     [files] = ok
(0)     [expiration] = noop
(0)     [logintime] = noop
(0)     [pap] = updated
(0)   } # authorize = updated
(0) Found Auth-Type = PAP
(0) # Executing group from file /opt/OmniVista_2500_NMS/services/freeradius-server/etc/raddb/sites-enabled/default
(0)   Auth-Type PAP {
(0) pap: Login attempt with password
(0) pap: Comparing with "known good" Cleartext-Password
(0) pap: ERROR: Cleartext password does not match "known good" password
(0) pap: Passwords don't match
(0)     [pap] = reject
(0)   } # Auth-Type PAP = reject
(0) Failed to authenticate the user
(0) WARNING: Unprintable characters in the password.  Double-check the shared secret on the server and the NAS!
(0) Using Post-Auth-Type Reject
(0) # Executing group from file /opt/OmniVista_2500_NMS/services/freeradius-server/etc/raddb/sites-enabled/default
(0)   Post-Auth-Type REJECT {
(0) attr_filter.access_reject: EXPAND %{User-Name}
(0) attr_filter.access_reject:    --> steve
(0) attr_filter.access_reject: Matched entry DEFAULT at line 11
(0)     [attr_filter.access_reject] = updated
(0)     [eap] = noop
(0)     policy remove_reply_message_if_eap {
(0)       if (&reply:EAP-Message && &reply:Reply-Message) {
(0)       if (&reply:EAP-Message && &reply:Reply-Message)  -> FALSE
(0)       else {
(0)         [noop] = noop
(0)       } # else = noop
(0)     } # policy remove_reply_message_if_eap = noop
(0)   } # Post-Auth-Type REJECT = updated
(0) Login incorrect (pap: Cleartext password does not match "known good" password): [steve/W??#????

Anyone can help me ?
Thanks in advance

**Comment by arun0704** [comment]
How did you resolve this issue @yunyexiangfeng

**Comment by yunyexiangfeng** [comment]
> How did you resolve this issue @yunyexiangfeng

I coded a fixed password in PAPAuthenticator.java
